import type { ToothClinicalLayer, ToothSurface, ToothVisualState } from "./types";

export const DDS_COLORS = {
  diagnosis: "#E53935",
  treatment: "#1E88E5",
  planned: "#FB8C00",
  selected: "#2E7D32",
  observation: "#757575",
  implant: "#8E24AA",
  primary: "#FBC02D",
  text: "#2B2B2B",
  tooth: "#FFFDF7",
  enamel: "#FFF8EA",
  temporaryCrown: "#CFE7F7",
  temporaryRestoration: "#D9EEF9",
  neutral: "#8A94A3",
} as const;

export const DDS_SURFACES: ToothSurface[] = [
  "VESTIBULAR",
  "LINGUAL",
  "PALATAL",
  "MESIAL",
  "DISTAL",
  "OCCLUSAL",
  "INCISAL",
];

export const DDS_LAYER_LABELS: Record<ToothClinicalLayer, string> = {
  STRUCTURAL: "Estructura",
  FINDING: "Hallazgo",
  DIAGNOSIS: "Diagnóstico",
  PLANNED: "Planificado",
  PERFORMED: "Realizado",
  OBSERVATION: "Observación",
};

export const DDS_STATE_LABELS: Record<ToothVisualState, string> = {
  HEALTHY: "Sano",
  OCCLUSAL_CARIES: "Caries oclusal",
  PROXIMAL_CARIES: "Caries proximal",
  CERVICAL_CARIES: "Caries cervical",
  SIMPLE_FILLING: "Obturación",
  MULTIPLE_FILLINGS: "Obturación múltiple",
  DEFINITIVE_CROWN: "Corona definitiva",
  TEMPORARY_CROWN: "Corona temporal",
  ENDODONTICS: "Endodoncia",
  POST: "Poste",
  IMPLANT: "Implante",
  FIXED_PROSTHESIS: "Prótesis fija",
  REMOVABLE_PROSTHESIS: "Prótesis removible",
  MISSING: "Ausente",
  TEMPORARY_RESTORATION: "Restauración temporal",
  SEALANT: "Sellante",
  NON_CARIOUS_CERVICAL_LESION: "Lesión cervical no cariosa",
  WEAR: "Desgaste",
  FRACTURE: "Fractura",
  MOBILITY: "Movilidad",
  PRIMARY_TOOTH: "Diente temporal",
  PLANNED_TREATMENT: "Tratamiento planificado",
  IN_PROGRESS_TREATMENT: "Tratamiento en proceso",
  OBSERVATION: "Observación",
};

export const DDS_VISUAL_PRIORITY: ToothVisualState[] = [
  "MISSING",
  "IMPLANT",
  "DEFINITIVE_CROWN",
  "TEMPORARY_CROWN",
  "FIXED_PROSTHESIS",
  "REMOVABLE_PROSTHESIS",
  "ENDODONTICS",
  "POST",
  "SIMPLE_FILLING",
  "MULTIPLE_FILLINGS",
  "TEMPORARY_RESTORATION",
  "SEALANT",
  "OCCLUSAL_CARIES",
  "PROXIMAL_CARIES",
  "CERVICAL_CARIES",
  "NON_CARIOUS_CERVICAL_LESION",
  "WEAR",
  "FRACTURE",
  "MOBILITY",
  "OBSERVATION",
  "PLANNED_TREATMENT",
  "IN_PROGRESS_TREATMENT",
  "PRIMARY_TOOTH",
  "HEALTHY",
];
