"""add installation completion marker

Revision ID: 03137f3bb487
Revises: 9e6650c0951d
Create Date: 2026-06-17 21:37:29.958328

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '03137f3bb487'
down_revision: str | Sequence[str] | None = '9e6650c0951d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('installation_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'installation_completed_at')
    # ### end Alembic commands ###

