"""add provisional electronic consent acceptance evidence

Revision ID: 20260801_0026
Revises: 20260801_0025
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "20260801_0026"
down_revision = "20260801_0025"
branch_labels = None
depends_on = None

PERMISSIONS = [
    ("consent.acceptance.read", "Consultar aceptación de consentimiento", "consent_acceptance", "Consultar estado y resumen de aceptación electrónica."),
    ("consent.acceptance.view_evidence", "Consultar evidencia de consentimiento", "consent_acceptance", "Consultar evidencia técnica restringida de aceptación."),
    ("consent.final_document.read", "Consultar documento final de consentimiento", "consent_acceptance", "Consultar metadatos del PDF final inmutable."),
    ("consent.final_document.download", "Descargar documento final de consentimiento", "consent_acceptance", "Descargar el PDF final autorizado."),
    ("consent.copy.resend", "Reenviar copia de consentimiento", "consent_acceptance", "Reenviar al paciente la copia del documento final."),
]
ROLE_PERMISSIONS = {
    "ADMINISTRATOR": ["consent.acceptance.read", "consent.final_document.read", "consent.final_document.download", "consent.copy.resend"],
    "DENTIST_ADMIN": [p[0] for p in PERMISSIONS],
    "DENTIST": ["consent.acceptance.read", "consent.acceptance.view_evidence", "consent.final_document.read", "consent.final_document.download"],
    "SECRETARY": ["consent.acceptance.read", "consent.final_document.read", "consent.final_document.download", "consent.copy.resend"],
}

def _seed_permissions():
    for code, name, module, description in PERMISSIONS:
        op.execute(sa.text("""INSERT INTO permisos (id,code,nombre,modulo,descripcion,is_active,created_at,updated_at)
        VALUES (gen_random_uuid(),:code,:name,:module,:description,true,now(),now())
        ON CONFLICT (code) DO UPDATE SET nombre=EXCLUDED.nombre,modulo=EXCLUDED.modulo,descripcion=EXCLUDED.descripcion,is_active=true,updated_at=now()""").bindparams(code=code,name=name,module=module,description=description))
    for role, codes in ROLE_PERMISSIONS.items():
        op.execute(sa.text("""INSERT INTO rol_permisos (id,empresa_id,rol_id,permiso_id,is_active,created_by,created_at,updated_at)
        SELECT gen_random_uuid(),r.empresa_id,r.id,p.id,true,r.created_by,now(),now() FROM roles r JOIN permisos p ON p.code=ANY(:codes)
        WHERE r.code=:role AND NOT EXISTS (SELECT 1 FROM rol_permisos rp WHERE rp.rol_id=r.id AND rp.permiso_id=p.id)""").bindparams(sa.bindparam("role",value=role),sa.bindparam("codes",value=codes,type_=postgresql.ARRAY(sa.String()))))

def _base_columns():
    return [sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False)]

def upgrade():
    _seed_permissions()
    op.add_column("consentimiento_instancias",sa.Column("signed_at",sa.DateTime(timezone=True),nullable=True))
    op.drop_constraint("ck_consent_instance_status","consentimiento_instancias",type_="check")
    op.create_check_constraint("ck_consent_instance_status","consentimiento_instancias","status IN ('DRAFT','READY_FOR_REVIEW','PENDING_SIGNATURE','SIGNED','VOIDED')")
    op.create_table("consentimiento_aceptaciones",
        sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("empresa_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("sede_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("paciente_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("consent_instance_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("access_session_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("public_session_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("otp_challenge_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("idempotency_key",sa.String(100),nullable=False),sa.Column("actor_type",sa.String(30),server_default="PATIENT_SELF",nullable=False),sa.Column("acting_on_own_behalf",sa.Boolean(),nullable=False),sa.Column("typed_full_name",sa.String(250),nullable=False),sa.Column("patient_name_snapshot",sa.String(250),nullable=False),sa.Column("patient_birth_date_snapshot",sa.Date(),nullable=False),sa.Column("patient_document_type_snapshot",sa.String(30),nullable=False),sa.Column("patient_document_number_snapshot",sa.String(80)),sa.Column("recipient_masked_snapshot",sa.String(220),nullable=False),sa.Column("declaration_set_code",sa.String(80),nullable=False),sa.Column("declarations_country_code",sa.String(2),nullable=False),sa.Column("declarations_locale",sa.String(10),nullable=False),sa.Column("declarations_version",sa.String(60),nullable=False),sa.Column("declarations_legal_status",sa.String(30),nullable=False),sa.Column("declarations_effective_from",sa.Date()),sa.Column("declarations_set_sha256",sa.String(64),nullable=False),sa.Column("test_document",sa.Boolean(),server_default=sa.true(),nullable=False),sa.Column("accepted_at",sa.DateTime(timezone=True),nullable=False),sa.Column("timezone_name",sa.String(100),nullable=False),sa.Column("local_datetime",sa.String(80),nullable=False),sa.Column("ip_hash",sa.String(64)),sa.Column("user_agent_summary",sa.String(500)),sa.Column("locale",sa.String(20)),sa.Column("correlation_id",sa.String(100),nullable=False),sa.Column("row_version",sa.Integer(),server_default="1",nullable=False),sa.Column("failure_reason",sa.String(500)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),
        sa.CheckConstraint("status IN ('INITIATED','SUBMITTED','COMPLETED','FAILED','INVALIDATED')",name="ck_consent_acceptance_status"),sa.UniqueConstraint("consent_instance_id",name="uq_consent_acceptance_instance"),sa.UniqueConstraint("access_session_id","idempotency_key",name="uq_consent_acceptance_idempotency"),sa.ForeignKeyConstraint(["empresa_id"],["empresas.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["sede_id"],["sedes.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["paciente_id"],["pacientes.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["consent_instance_id"],["consentimiento_instancias.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["access_session_id"],["consentimiento_sesiones_acceso.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["public_session_id"],["consentimiento_sesiones_publicas.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["otp_challenge_id"],["consentimiento_otp_desafios.id"],ondelete="RESTRICT"))
    op.create_index("ix_consent_acceptance_company_instance","consentimiento_aceptaciones",["empresa_id","consent_instance_id"])
    op.create_table("consentimiento_aceptacion_declaraciones",*_base_columns(),sa.Column("empresa_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("acceptance_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("code",sa.String(80),nullable=False),sa.Column("text_snapshot",sa.Text(),nullable=False),sa.Column("text_sha256",sa.String(64),nullable=False),sa.Column("declaration_version",sa.String(60),nullable=False),sa.Column("required",sa.Boolean(),nullable=False),sa.Column("accepted",sa.Boolean(),nullable=False),sa.Column("responded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("order_number",sa.Integer(),nullable=False),sa.UniqueConstraint("acceptance_id","code",name="uq_consent_acceptance_declaration_code"),sa.ForeignKeyConstraint(["empresa_id"],["empresas.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["acceptance_id"],["consentimiento_aceptaciones.id"],ondelete="RESTRICT"))
    op.create_table("consentimiento_firmas_artefactos",*_base_columns(),sa.Column("empresa_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("acceptance_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("storage_key",sa.String(700),nullable=False),sa.Column("signature_type",sa.String(30),nullable=False),sa.Column("typed_name_snapshot",sa.String(250),nullable=False),sa.Column("graphic_present",sa.Boolean(),nullable=False),sa.Column("sanitization_version",sa.String(50),nullable=False),sa.Column("sha256",sa.String(64),nullable=False),sa.Column("mime_type",sa.String(80),nullable=False),sa.Column("byte_size",sa.BigInteger(),nullable=False),sa.Column("width",sa.Integer(),nullable=False),sa.Column("height",sa.Integer(),nullable=False),sa.UniqueConstraint("acceptance_id",name="uq_consent_signature_acceptance"),sa.ForeignKeyConstraint(["empresa_id"],["empresas.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["acceptance_id"],["consentimiento_aceptaciones.id"],ondelete="RESTRICT"))
    op.create_table("consentimiento_evidencia_manifiestos",*_base_columns(),sa.Column("empresa_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("acceptance_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("schema_version",sa.String(30),nullable=False),sa.Column("manifest",postgresql.JSONB(),nullable=False),sa.Column("manifest_sha256",sa.String(64),nullable=False),sa.Column("storage_key",sa.String(700),nullable=False),sa.UniqueConstraint("acceptance_id",name="uq_consent_evidence_acceptance"),sa.ForeignKeyConstraint(["empresa_id"],["empresas.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["acceptance_id"],["consentimiento_aceptaciones.id"],ondelete="RESTRICT"))
    op.create_table("consentimiento_documentos_finales",*_base_columns(),sa.Column("empresa_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("consent_instance_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("acceptance_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("evidence_manifest_id",postgresql.UUID(as_uuid=True)),sa.Column("storage_key",sa.String(700),nullable=False),sa.Column("filename",sa.String(250),nullable=False),sa.Column("mime_type",sa.String(80),server_default="application/pdf",nullable=False),sa.Column("byte_size",sa.BigInteger(),nullable=False),sa.Column("sha256",sa.String(64),nullable=False),sa.Column("generated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("renderer_version",sa.String(60),nullable=False),sa.Column("immutable",sa.Boolean(),server_default=sa.true(),nullable=False),sa.Column("download_count",sa.Integer(),server_default="0",nullable=False),sa.Column("public_download_token_hash",sa.String(64)),sa.Column("public_download_expires_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("consent_instance_id",name="uq_consent_final_document_instance"),sa.ForeignKeyConstraint(["empresa_id"],["empresas.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["consent_instance_id"],["consentimiento_instancias.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["acceptance_id"],["consentimiento_aceptaciones.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["evidence_manifest_id"],["consentimiento_evidencia_manifiestos.id"],ondelete="RESTRICT"))
    op.create_index("ix_consent_final_document_download_hash","consentimiento_documentos_finales",["public_download_token_hash"],unique=True)
    op.create_table("consentimiento_entregas_copia",*_base_columns(),sa.Column("empresa_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("consent_instance_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("acceptance_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("final_document_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("status",sa.String(20),server_default="PENDING",nullable=False),sa.Column("channel",sa.String(20),server_default="EMAIL",nullable=False),sa.Column("recipient_masked",sa.String(220),nullable=False),sa.Column("attempted_at",sa.DateTime(timezone=True),nullable=False),sa.Column("delivered_at",sa.DateTime(timezone=True)),sa.Column("error_code",sa.String(100)),sa.Column("requested_by",postgresql.UUID(as_uuid=True)),sa.CheckConstraint("status IN ('PENDING','SENT','FAILED')",name="ck_consent_copy_delivery_status"),sa.ForeignKeyConstraint(["empresa_id"],["empresas.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["consent_instance_id"],["consentimiento_instancias.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["acceptance_id"],["consentimiento_aceptaciones.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["final_document_id"],["consentimiento_documentos_finales.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["requested_by"],["usuarios.id"],ondelete="SET NULL"))
    op.create_index("ix_consent_copy_delivery_instance","consentimiento_entregas_copia",["empresa_id","consent_instance_id"])

def downgrade():
    op.drop_index("ix_consent_copy_delivery_instance",table_name="consentimiento_entregas_copia");op.drop_table("consentimiento_entregas_copia")
    op.drop_index("ix_consent_final_document_download_hash",table_name="consentimiento_documentos_finales");op.drop_table("consentimiento_documentos_finales")
    op.drop_table("consentimiento_evidencia_manifiestos");op.drop_table("consentimiento_firmas_artefactos");op.drop_table("consentimiento_aceptacion_declaraciones")
    op.drop_index("ix_consent_acceptance_company_instance",table_name="consentimiento_aceptaciones");op.drop_table("consentimiento_aceptaciones")
    op.drop_constraint("ck_consent_instance_status","consentimiento_instancias",type_="check");op.create_check_constraint("ck_consent_instance_status","consentimiento_instancias","status IN ('DRAFT','READY_FOR_REVIEW','PENDING_SIGNATURE','VOIDED')")
    op.drop_column("consentimiento_instancias","signed_at")
