"""create base security models

Revision ID: 9e6650c0951d
Revises: 20260617_0001
Create Date: 2026-06-17 21:29:41.512921

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '9e6650c0951d'
down_revision: str | Sequence[str] | None = '20260617_0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='Activa', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas')),
    sa.UniqueConstraint('slug', name=op.f('uq_empresas_slug'))
    )
    op.create_table('permisos',
    sa.Column('code', sa.String(length=150), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('modulo', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permisos')),
    sa.UniqueConstraint('code', name=op.f('uq_permisos_code'))
    )
    op.create_table('sedes',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='Activa', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_sedes_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sedes')),
    sa.UniqueConstraint('empresa_id', 'nombre', name='uq_sedes_empresa_nombre')
    )
    op.create_index(op.f('ix_sedes_empresa_id'), 'sedes', ['empresa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('default_sede_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('correo', sa.String(length=320), nullable=False),
    sa.Column('correo_normalizado', sa.String(length=320), nullable=False),
    sa.Column('celular', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auth_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('estado', sa.String(length=20), server_default='Pendiente', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('auth_version >= 1', name=op.f('ck_usuarios_auth_version_positive')),
    sa.CheckConstraint('failed_login_attempts >= 0', name=op.f('ck_usuarios_failed_login_attempts_nonnegative')),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name='fk_usuarios_created_by_usuarios', use_alter=True),
    sa.ForeignKeyConstraint(['default_sede_id'], ['sedes.id'], name=op.f('fk_usuarios_default_sede_id_sedes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_usuarios_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('correo_normalizado', name='uq_usuarios_correo_normalizado')
    )
    op.create_index(op.f('ix_usuarios_default_sede_id'), 'usuarios', ['default_sede_id'], unique=False)
    op.create_index(op.f('ix_usuarios_empresa_id'), 'usuarios', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuarios_locked_until'), 'usuarios', ['locked_until'], unique=False)
    op.create_foreign_key(
        'fk_empresas_created_by_usuarios',
        'empresas',
        'usuarios',
        ['created_by'],
        ['id'],
    )
    op.create_foreign_key(
        'fk_sedes_created_by_usuarios',
        'sedes',
        'usuarios',
        ['created_by'],
        ['id'],
    )
    op.create_foreign_key(
        'fk_usuarios_created_by_usuarios',
        'usuarios',
        'usuarios',
        ['created_by'],
        ['id'],
    )
    op.create_table('auth_attempts',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('email_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('resultado', sa.String(length=30), nullable=False),
    sa.Column('motivo_fallo', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_auth_attempts_empresa_id_empresas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_auth_attempts_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_attempts'))
    )
    op.create_index(op.f('ix_auth_attempts_empresa_id'), 'auth_attempts', ['empresa_id'], unique=False)
    op.create_index('ix_auth_attempts_fingerprint_fecha', 'auth_attempts', ['email_fingerprint', 'fecha'], unique=False)
    op.create_index(op.f('ix_auth_attempts_ip_address'), 'auth_attempts', ['ip_address'], unique=False)
    op.create_index('ix_auth_attempts_ip_fecha', 'auth_attempts', ['ip_address', 'fecha'], unique=False)
    op.create_index('ix_auth_attempts_usuario_fecha', 'auth_attempts', ['usuario_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_auth_attempts_usuario_id'), 'auth_attempts', ['usuario_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('sede_activa_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('token_family_id', sa.UUID(), nullable=False),
    sa.Column('rotation_counter', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_auth_sessions_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by'], ['usuarios.id'], name=op.f('fk_auth_sessions_revoked_by_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sede_activa_id'], ['sedes.id'], name=op.f('fk_auth_sessions_sede_activa_id_sedes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_auth_sessions_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name='uq_auth_sessions_refresh_token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_empresa_id'), 'auth_sessions', ['empresa_id'], unique=False)
    op.create_index('ix_auth_sessions_expires_at', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_ip_address'), 'auth_sessions', ['ip_address'], unique=False)
    op.create_index(op.f('ix_auth_sessions_sede_activa_id'), 'auth_sessions', ['sede_activa_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_token_family_id'), 'auth_sessions', ['token_family_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_usuario_id'), 'auth_sessions', ['usuario_id'], unique=False)
    op.create_index('ix_auth_sessions_usuario_last_seen', 'auth_sessions', ['usuario_id', 'last_seen_at'], unique=False)
    op.create_table('roles',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('fk_roles_created_by_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_roles_empresa_id_empresas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('empresa_id', 'code', name='uq_roles_empresa_code')
    )
    op.create_index(op.f('ix_roles_empresa_id'), 'roles', ['empresa_id'], unique=False)
    op.create_table('usuario_sedes',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('sede_id', sa.UUID(), nullable=False),
    sa.Column('es_principal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('fk_usuario_sedes_created_by_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_usuario_sedes_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], name=op.f('fk_usuario_sedes_sede_id_sedes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_sedes_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario_sedes')),
    sa.UniqueConstraint('usuario_id', 'sede_id', name='uq_usuario_sedes_usuario_sede')
    )
    op.create_index(op.f('ix_usuario_sedes_empresa_id'), 'usuario_sedes', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuario_sedes_sede_id'), 'usuario_sedes', ['sede_id'], unique=False)
    op.create_index(op.f('ix_usuario_sedes_usuario_id'), 'usuario_sedes', ['usuario_id'], unique=False)
    op.create_table('auditoria_eventos',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('resultado', sa.String(length=30), nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_origen', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_auditoria_eventos_empresa_id_empresas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['auth_sessions.id'], name=op.f('fk_auditoria_eventos_session_id_auth_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_auditoria_eventos_usuario_id_usuarios'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria_eventos'))
    )
    op.create_index('ix_auditoria_eventos_empresa_fecha', 'auditoria_eventos', ['empresa_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_empresa_id'), 'auditoria_eventos', ['empresa_id'], unique=False)
    op.create_index('ix_auditoria_eventos_session_id', 'auditoria_eventos', ['session_id'], unique=False)
    op.create_index('ix_auditoria_eventos_usuario_fecha', 'auditoria_eventos', ['usuario_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_auditoria_eventos_usuario_id'), 'auditoria_eventos', ['usuario_id'], unique=False)
    op.create_table('rol_permisos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('permiso_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('fk_rol_permisos_created_by_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_rol_permisos_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], name=op.f('fk_rol_permisos_permiso_id_permisos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_rol_permisos_rol_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rol_permisos')),
    sa.UniqueConstraint('rol_id', 'permiso_id', name='uq_rol_permisos_rol_permiso')
    )
    op.create_index(op.f('ix_rol_permisos_empresa_id'), 'rol_permisos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_rol_permisos_permiso_id'), 'rol_permisos', ['permiso_id'], unique=False)
    op.create_index(op.f('ix_rol_permisos_rol_id'), 'rol_permisos', ['rol_id'], unique=False)
    op.create_table('usuario_roles',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['usuarios.id'], name=op.f('fk_usuario_roles_created_by_usuarios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_usuario_roles_empresa_id_empresas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], name=op.f('fk_usuario_roles_rol_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_usuario_roles_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario_roles')),
    sa.UniqueConstraint('usuario_id', 'rol_id', name='uq_usuario_roles_usuario_rol')
    )
    op.create_index(op.f('ix_usuario_roles_empresa_id'), 'usuario_roles', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_usuario_roles_rol_id'), 'usuario_roles', ['rol_id'], unique=False)
    op.create_index(op.f('ix_usuario_roles_usuario_id'), 'usuario_roles', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_sedes_created_by_usuarios',
        'sedes',
        type_='foreignkey',
    )
    op.drop_constraint(
        'fk_empresas_created_by_usuarios',
        'empresas',
        type_='foreignkey',
    )
    op.drop_constraint(
        'fk_usuarios_created_by_usuarios',
        'usuarios',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_usuario_roles_usuario_id'), table_name='usuario_roles')
    op.drop_index(op.f('ix_usuario_roles_rol_id'), table_name='usuario_roles')
    op.drop_index(op.f('ix_usuario_roles_empresa_id'), table_name='usuario_roles')
    op.drop_table('usuario_roles')
    op.drop_index(op.f('ix_rol_permisos_rol_id'), table_name='rol_permisos')
    op.drop_index(op.f('ix_rol_permisos_permiso_id'), table_name='rol_permisos')
    op.drop_index(op.f('ix_rol_permisos_empresa_id'), table_name='rol_permisos')
    op.drop_table('rol_permisos')
    op.drop_index(op.f('ix_auditoria_eventos_usuario_id'), table_name='auditoria_eventos')
    op.drop_index('ix_auditoria_eventos_usuario_fecha', table_name='auditoria_eventos')
    op.drop_index('ix_auditoria_eventos_session_id', table_name='auditoria_eventos')
    op.drop_index(op.f('ix_auditoria_eventos_empresa_id'), table_name='auditoria_eventos')
    op.drop_index('ix_auditoria_eventos_empresa_fecha', table_name='auditoria_eventos')
    op.drop_table('auditoria_eventos')
    op.drop_index(op.f('ix_usuario_sedes_usuario_id'), table_name='usuario_sedes')
    op.drop_index(op.f('ix_usuario_sedes_sede_id'), table_name='usuario_sedes')
    op.drop_index(op.f('ix_usuario_sedes_empresa_id'), table_name='usuario_sedes')
    op.drop_table('usuario_sedes')
    op.drop_index(op.f('ix_roles_empresa_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_auth_sessions_usuario_last_seen', table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_usuario_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_family_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_sede_activa_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_ip_address'), table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_expires_at', table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_empresa_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_attempts_usuario_id'), table_name='auth_attempts')
    op.drop_index('ix_auth_attempts_usuario_fecha', table_name='auth_attempts')
    op.drop_index('ix_auth_attempts_ip_fecha', table_name='auth_attempts')
    op.drop_index(op.f('ix_auth_attempts_ip_address'), table_name='auth_attempts')
    op.drop_index('ix_auth_attempts_fingerprint_fecha', table_name='auth_attempts')
    op.drop_index(op.f('ix_auth_attempts_empresa_id'), table_name='auth_attempts')
    op.drop_table('auth_attempts')
    op.drop_index(op.f('ix_usuarios_locked_until'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_empresa_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_default_sede_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sedes_empresa_id'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_table('permisos')
    op.drop_table('empresas')
    # ### end Alembic commands ###
