"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import type { ReactNode } from "react";
import { Alert } from "@/components/shared/Alert";
import { ApiError } from "@/services/apiClient";
import { addOrthodonticCatalogOption, createOrthodonticEvolution, getOrthodonticCatalog, listOrthodonticEvolutions, signOrthodonticEvolution, updateOrthodonticEvolution } from "@/services/orthodonticEvolutionService";
import type { OrthodonticCase } from "@/types/orthodonticCase";
import type { CatalogType, OrthodonticCatalog, OrthodonticEvolution, OrthodonticEvolutionPayload, OrthodonticMiniScrew } from "@/types/orthodonticEvolution";

const emptyPayload: OrthodonticEvolutionPayload = { performed_summary: null, notes: null, upper_material_option_id: null, upper_size_option_id: null, lower_material_option_id: null, lower_size_option_id: null, upper_aligner_note: null, lower_aligner_note: null, elastic_type: null, elastic_configuration: null, mini_screws: [], next_session_instructions: null, next_control_option_id: null, alert_text: null, alert_active: false };
const formatDate = (value: string) => new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export function OrthodonticEvolutionPanel({ orthodonticCase, accessAllowed, onChanged }: { orthodonticCase: OrthodonticCase; accessAllowed: boolean; onChanged: () => Promise<void> }) {
  const [items, setItems] = useState<OrthodonticEvolution[]>([]);
  const [catalogs, setCatalogs] = useState<Record<CatalogType, OrthodonticCatalog> | null>(null);
  const [editing, setEditing] = useState<OrthodonticEvolution | "new" | null>(null);
  const [form, setForm] = useState<OrthodonticEvolutionPayload>(emptyPayload);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);

  const load = useCallback(async () => {
    const [evolutions, material, size, control] = await Promise.all([listOrthodonticEvolutions(orthodonticCase.id), getOrthodonticCatalog("ARCH_MATERIAL"), getOrthodonticCatalog("ARCH_SIZE"), getOrthodonticCatalog("CONTROL_INTERVAL")]);
    setItems(evolutions.items); setCatalogs({ ARCH_MATERIAL: material, ARCH_SIZE: size, CONTROL_INTERVAL: control });
  }, [orthodonticCase.id]);
  useEffect(() => { void load().catch((caught) => setError(caught instanceof ApiError ? caught.detail ?? caught.message : "No fue posible cargar las evoluciones.")); }, [load]);

  function edit(item: OrthodonticEvolution) { setEditing(item); setForm({ performed_summary: item.performed_summary, notes: item.notes, upper_material_option_id: item.upper_material.option_id, upper_size_option_id: item.upper_size.option_id, lower_material_option_id: item.lower_material.option_id, lower_size_option_id: item.lower_size.option_id, upper_aligner_note: item.upper_aligner_note, lower_aligner_note: item.lower_aligner_note, elastic_type: item.elastic_type, elastic_configuration: item.elastic_configuration, mini_screws: item.mini_screws.map(({ screw_type, location, material, measurement, notes }) => ({ screw_type, location, material, measurement, notes })), next_session_instructions: item.next_session_instructions, next_control_option_id: item.next_control.option_id, alert_text: item.alert_text, alert_active: item.alert_active }); setError(null); setMessage(null); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const saved = editing === "new" ? await createOrthodonticEvolution(orthodonticCase.id, form) : await updateOrthodonticEvolution(editing as OrthodonticEvolution, form); setMessage("Borrador de evolución guardado."); setEditing(null); await load(); await onChanged(); return saved; } catch (caught) { setError(caught instanceof ApiError ? caught.detail ?? caught.message : "No fue posible guardar la evolución."); } finally { setBusy(false); } }
  async function sign(item: OrthodonticEvolution) { setBusy(true); setError(null); try { await signOrthodonticEvolution(item); setMessage("Evolución firmada e incorporada al resumen."); setEditing(null); await load(); await onChanged(); } catch (caught) { setError(caught instanceof ApiError ? caught.detail ?? caught.message : "No fue posible firmar la evolución."); } finally { setBusy(false); } }
  async function addOption(type: CatalogType) { const label = window.prompt("Nombre de la nueva opción"); if (!label?.trim()) return; let value: number | undefined; let unit: "WEEK" | "MONTH" | undefined; if (type === "CONTROL_INTERVAL") { const raw = window.prompt("Cantidad (número entero)"); const chosen = window.prompt("Unidad: WEEK o MONTH", "WEEK")?.toUpperCase(); value = Number(raw); unit = chosen === "MONTH" ? "MONTH" : "WEEK"; if (!Number.isInteger(value) || value < 1) { setError("La cantidad del intervalo no es válida."); return; } } try { await addOrthodonticCatalogOption(type, label, value, unit); await load(); } catch (caught) { setError(caught instanceof ApiError ? caught.detail ?? caught.message : "No fue posible crear la opción."); } }

  if (!catalogs) return <section className="rounded-2xl border bg-white p-6"><p className="text-sm text-slate-500">Cargando evoluciones…</p>{error && <Alert tone="error">{error}</Alert>}</section>;
  const writable = orthodonticCase.status === "ACTIVE" && accessAllowed;
  return <div className="space-y-5">
    {message && <Alert>{message}</Alert>}{error && <Alert tone="error">{error}</Alert>}
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">Evolución de Ortodoncia</h2><p className="text-sm text-slate-500">Borradores editables y controles firmados inmutables.</p></div>{writable && editing === null && <button type="button" onClick={() => { setForm(emptyPayload); setEditing("new"); }} className="rounded-xl bg-green-700 px-4 py-2 font-bold text-white">Nueva evolución</button>}</div>
    {!accessAllowed && <Alert tone="warning">Tu acceso de Ortodoncia ya no está habilitado. El historial permanece disponible en modo de solo lectura.</Alert>}
    {accessAllowed && orthodonticCase.status === "SUSPENDED" && <Alert tone="warning">Este caso está suspendido. Reactívalo para registrar, editar o firmar evoluciones.</Alert>}
    {orthodonticCase.status === "COMPLETED" && <Alert tone="info">Este caso está cerrado y se conserva como historial clínico.</Alert>}
    {accessAllowed && orthodonticCase.status === "DRAFT" && <Alert tone="info">Inicia el tratamiento para registrar evoluciones.</Alert>}
    {editing && <form onSubmit={save} className="space-y-6 rounded-2xl border bg-white p-5 shadow-sm">
      <Section title="Consulta"><TextArea label="Qué se hizo" value={form.performed_summary} onChange={(value) => setForm({ ...form, performed_summary: value || null })} /><TextArea label="Notas de evolución" value={form.notes} onChange={(value) => setForm({ ...form, notes: value || null })} /></Section>
      <div className="grid gap-5 md:grid-cols-2"><Arch title="Arco superior" material={form.upper_material_option_id} size={form.upper_size_option_id} catalogs={catalogs} onMaterial={(value) => setForm({ ...form, upper_material_option_id: value })} onSize={(value) => setForm({ ...form, upper_size_option_id: value })} onAdd={addOption} /><Arch title="Arco inferior" material={form.lower_material_option_id} size={form.lower_size_option_id} catalogs={catalogs} onMaterial={(value) => setForm({ ...form, lower_material_option_id: value })} onSize={(value) => setForm({ ...form, lower_size_option_id: value })} onAdd={addOption} /></div>
      <Section title="Alineadores"><div className="grid gap-4 md:grid-cols-2"><Input label="Alineador superior" value={form.upper_aligner_note} onChange={(value) => setForm({ ...form, upper_aligner_note: value || null })} /><Input label="Alineador inferior" value={form.lower_aligner_note} onChange={(value) => setForm({ ...form, lower_aligner_note: value || null })} /></div></Section>
      <Section title="Elásticos"><div className="grid gap-4 md:grid-cols-2"><Input label="Tipo de elásticos" value={form.elastic_type} onChange={(value) => setForm({ ...form, elastic_type: value || null })} /><Input label="Configuración" value={form.elastic_configuration} onChange={(value) => setForm({ ...form, elastic_configuration: value || null })} /></div></Section>
      <Section title="Microtornillos"><div className="space-y-3">{form.mini_screws.map((screw, index) => <MiniScrewFields key={index} value={screw} onChange={(value) => setForm({ ...form, mini_screws: form.mini_screws.map((item, position) => position === index ? value : item) })} onRemove={() => setForm({ ...form, mini_screws: form.mini_screws.filter((_, position) => position !== index) })} />)}<button type="button" onClick={() => setForm({ ...form, mini_screws: [...form.mini_screws, { screw_type: "SELF_TAPPING", location: "INTERRADICULAR", material: "TITANIUM", measurement: "", notes: null }] })} className="rounded-xl border px-3 py-2 text-sm font-bold">Agregar microtornillo</button></div></Section>
      <Section title="Próxima sesión"><TextArea label="Indicaciones próxima sesión" value={form.next_session_instructions} onChange={(value) => setForm({ ...form, next_session_instructions: value || null })} /><Select label="Próximo control" value={form.next_control_option_id} options={catalogs.CONTROL_INTERVAL.items} onChange={(value) => setForm({ ...form, next_control_option_id: value })} />{catalogs.CONTROL_INTERVAL.can_manage && <button type="button" onClick={() => void addOption("CONTROL_INTERVAL")} className="text-sm font-bold text-green-700">Agregar opción de control</button>}</Section>
      <Section title="Alertas"><TextArea label="Alerta" value={form.alert_text} onChange={(value) => setForm({ ...form, alert_text: value || null })} /><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={form.alert_active} onChange={(event) => setForm({ ...form, alert_active: event.target.checked })} />Alerta activa</label></Section>
      <div className="flex gap-2"><button disabled={busy} className="rounded-xl bg-green-700 px-4 py-2 font-bold text-white disabled:opacity-50">Guardar borrador</button><button type="button" onClick={() => setEditing(null)} className="rounded-xl border px-4 py-2 font-bold">Cancelar</button></div>
    </form>}
    <section className="space-y-3">{items.length === 0 && <div className="rounded-2xl border bg-white p-6 text-sm text-slate-500">Sin evoluciones de Ortodoncia registradas.</div>}{items.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-black">{item.status === "SIGNED" ? "Evolución firmada" : "Borrador"}</p><p className="text-sm text-slate-500">{formatDate(item.attended_at)} · {item.professional_name}</p>{item.integrity_status === "FAIL" && <p className="mt-1 text-sm font-bold text-red-700">No fue posible verificar la integridad de esta evolución.</p>}</div><div className="flex gap-2">{item.status === "DRAFT" && writable && <><button type="button" onClick={() => edit(item)} className="rounded-xl border px-3 py-2 text-sm font-bold">Editar</button><button type="button" disabled={busy} onClick={() => void sign(item)} className="rounded-xl bg-green-700 px-3 py-2 text-sm font-bold text-white">Firmar</button></>}</div></div><div className="mt-4 grid gap-3 text-sm md:grid-cols-2"><Value label="Qué se hizo" value={item.performed_summary} /><Value label="Próximo control" value={item.next_control.label ? `${item.next_control.label}${item.suggested_next_control_date ? ` · ${item.suggested_next_control_date}` : ""}` : null} /><Value label="Arco superior" value={[item.upper_material.label, item.upper_size.label].filter(Boolean).join(" · ") || null} /><Value label="Arco inferior" value={[item.lower_material.label, item.lower_size.label].filter(Boolean).join(" · ") || null} /></div>{item.notes && <details className="mt-4"><summary className="cursor-pointer text-sm font-bold">Ver detalle clínico</summary><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{item.notes}</p></details>}</article>)}</section>
  </div>;
}

function Section({ title, children }: { title: string; children: ReactNode }) { return <fieldset className="space-y-4"><legend className="mb-3 font-black">{title}</legend>{children}</fieldset>; }
function Input({ label, value, onChange }: { label: string; value: string | null; onChange: (value: string) => void }) { return <label className="block text-sm font-bold">{label}<input value={value ?? ""} onChange={(event) => onChange(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal" /></label>; }
function TextArea({ label, value, onChange }: { label: string; value: string | null; onChange: (value: string) => void }) { return <label className="block text-sm font-bold">{label}<textarea value={value ?? ""} onChange={(event) => onChange(event.target.value)} rows={3} className="mt-1 w-full rounded-xl border p-3 font-normal" /></label>; }
function Select({ label, value, options, onChange }: { label: string; value: string | null; options: OrthodonticCatalog["items"]; onChange: (value: string | null) => void }) { return <label className="block text-sm font-bold">{label}<select value={value ?? ""} onChange={(event) => onChange(event.target.value || null)} className="mt-1 min-h-11 w-full rounded-xl border bg-white px-3 font-normal"><option value="">Sin registrar</option>{options.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>; }
function Arch({ title, material, size, catalogs, onMaterial, onSize, onAdd }: { title: string; material: string | null; size: string | null; catalogs: Record<CatalogType, OrthodonticCatalog>; onMaterial: (value: string | null) => void; onSize: (value: string | null) => void; onAdd: (type: CatalogType) => Promise<void> }) { return <Section title={title}><Select label="Material" value={material} options={catalogs.ARCH_MATERIAL.items} onChange={onMaterial} /><Select label="Tamaño" value={size} options={catalogs.ARCH_SIZE.items} onChange={onSize} />{catalogs.ARCH_MATERIAL.can_manage && <div className="flex gap-3"><button type="button" onClick={() => void onAdd("ARCH_MATERIAL")} className="text-sm font-bold text-green-700">Agregar material</button><button type="button" onClick={() => void onAdd("ARCH_SIZE")} className="text-sm font-bold text-green-700">Agregar tamaño</button></div>}</Section>; }
function MiniScrewFields({ value, onChange, onRemove }: { value: Omit<OrthodonticMiniScrew, "id" | "sort_order">; onChange: (value: Omit<OrthodonticMiniScrew, "id" | "sort_order">) => void; onRemove: () => void }) { return <div className="grid gap-3 rounded-xl border p-3 md:grid-cols-2"><SelectRaw label="Tipo" value={value.screw_type} options={[["SELF_TAPPING", "Autoroscante"], ["SELF_DRILLING", "Autoperforante"]]} onChange={(screw_type) => onChange({ ...value, screw_type: screw_type as OrthodonticMiniScrew["screw_type"] })} /><SelectRaw label="Ubicación" value={value.location} options={[["INTERRADICULAR", "Interradicular"], ["PALATAL", "Palatino"], ["RETROMOLAR", "Retromolar"], ["INFRAZYGOMATIC_OR_ANTERIOR_ALVEOLAR", "Infrazigomática o alveolar anterior"]]} onChange={(location) => onChange({ ...value, location: location as OrthodonticMiniScrew["location"] })} /><SelectRaw label="Material" value={value.material} options={[["TITANIUM", "Titanio"], ["STEEL", "Acero"]]} onChange={(material) => onChange({ ...value, material: material as OrthodonticMiniScrew["material"] })} /><Input label="Medida" value={value.measurement} onChange={(measurement) => onChange({ ...value, measurement })} /><button type="button" onClick={onRemove} className="justify-self-start text-sm font-bold text-red-700">Quitar</button></div>; }
function SelectRaw({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: string) => void }) { return <label className="block text-sm font-bold">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-white px-3 font-normal">{options.map(([code, text]) => <option key={code} value={code}>{text}</option>)}</select></label>; }
function Value({ label, value }: { label: string; value: string | null }) { return <div><p className="font-bold text-slate-500">{label}</p><p>{value || "Sin registrar"}</p></div>; }
