"use client";
import { useEffect, useState } from "react";
import { Alert } from "@/components/shared/Alert";
import { downloadConsentFinalDocument, getConsentAcceptance, resendConsentCopy, type ConsentAcceptanceSummary } from "@/services/consentInstanceService";

export function ConsentAcceptancePanel({instanceId,canRead,canDownload,canResend}:{instanceId:string;canRead:boolean;canDownload:boolean;canResend:boolean}){
  const [summary,setSummary]=useState<ConsentAcceptanceSummary|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>{if(canRead)getConsentAcceptance(instanceId).then(setSummary).catch(()=>setError("No fue posible consultar el registro de aceptación."));},[canRead,instanceId]);
  async function download(){setBusy(true);try{const blob=await downloadConsentFinalDocument(instanceId);const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="consentimiento-final.pdf";anchor.click();URL.revokeObjectURL(url);}catch{setError("No fue posible descargar el documento final.");}finally{setBusy(false);}}
  async function resend(){setBusy(true);try{const value=await resendConsentCopy(instanceId);setSummary(current=>current?{...current,copy_delivery_status:value.status}:current);}catch{setError("No fue posible reenviar la copia.");}finally{setBusy(false);}}
  return <section className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50/50 p-4"><h4 className="font-black text-emerald-950">Consentimiento aceptado</h4><p className="text-xs text-emerald-900">Registro electrónico generado por Dentia con trazabilidad técnica de la aceptación.</p>{error&&<Alert tone="error">{error}</Alert>}{summary&&<div className="mt-3 space-y-2 text-sm">{summary.test_document&&<p role="alert" className="rounded-lg border-2 border-red-700 bg-red-50 p-2 text-center text-xs font-black text-red-800">{summary.test_notice}</p>}<p><b>Paciente:</b> {summary.patient_name}</p><p><b>Jurisdicción:</b> {summary.declarations_country_code} · {summary.declarations_locale}</p><p><b>Estado jurídico:</b> {summary.declarations_legal_status}</p><p><b>Fecha:</b> {new Date(summary.accepted_at).toLocaleString()}</p><p className="break-all text-xs"><b>SHA-256:</b> {summary.final_document_sha256}</p><p><b>Copia:</b> {summary.copy_delivery_status??"Sin intento"}</p><div className="flex gap-2">{canDownload&&<button disabled={busy} onClick={()=>void download()} className="rounded-lg bg-emerald-700 px-3 py-2 font-bold text-white">Descargar PDF</button>}{canResend&&<button disabled={busy} onClick={()=>void resend()} className="rounded-lg border border-emerald-300 px-3 py-2 font-bold">Reenviar copia</button>}</div></div>}</section>;
}
