"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { Alert } from "@/components/shared/Alert";
import { issueConsentAccess, listConsentAccess, listConsentAccessAudit, listConsentClarifications, reissueConsentAccess, resolveConsentClarification, revokeConsentAccess } from "@/services/consentInstanceService";
import type { ConsentAccessAudit, ConsentAccessSession, ConsentClarification } from "@/types/consentInstance";
import { copyTextSecurely } from "@/lib/secureClipboard.mjs";

export function ConsentAccessPanel({ instanceId, canIssue, canRead, canRevoke, canReissue, canManageClarifications, canViewAudit }: { instanceId:string; canIssue:boolean; canRead:boolean; canRevoke:boolean; canReissue:boolean; canManageClarifications:boolean; canViewAudit:boolean }) {
  const [sessions,setSessions]=useState<ConsentAccessSession[]>([]); const [clarifications,setClarifications]=useState<ConsentClarification[]>([]); const [audit,setAudit]=useState<ConsentAccessAudit[]>([]); const [issued,setIssued]=useState<ConsentAccessSession|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [copyState,setCopyState]=useState<"idle"|"copied"|"manual">("idle"); const linkInputRef=useRef<HTMLInputElement>(null);
  const load=useCallback(async()=>{if(!canRead)return;try{setSessions(await listConsentAccess(instanceId));if(canManageClarifications)setClarifications(await listConsentClarifications(instanceId));}catch{setError("No fue posible consultar el acceso del paciente.");}},[canManageClarifications,canRead,instanceId]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{setCopyState("idle");},[issued?.public_url]);
  async function create(reissue=false){setBusy(true);setError(null);try{const value=reissue?await reissueConsentAccess(instanceId):await issueConsentAccess(instanceId);setIssued(value);await load();}catch(e){setError(e instanceof Error?e.message:"No fue posible generar el acceso.");}finally{setBusy(false);}}
  async function revoke(item:ConsentAccessSession){const reason=window.prompt("Motivo de revocación (mínimo 5 caracteres):")?.trim();if(!reason)return;setBusy(true);try{await revokeConsentAccess(instanceId,item.id,reason);setIssued(null);await load();}catch(e){setError(e instanceof Error?e.message:"No fue posible revocar.");}finally{setBusy(false);}}
  async function copyIssuedLink(){if(!issued?.public_url)return;setCopyState(await copyTextSecurely(issued.public_url)?"copied":"manual");}
  function selectIssuedLink(){const input=linkInputRef.current;if(!input)return;input.focus();input.select();input.setSelectionRange(0,input.value.length);}
  const active=sessions.find(x=>!["REVOKED","EXPIRED"].includes(x.status));
  return <section className="mt-5 rounded-xl border border-sky-200 bg-sky-50/50 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h4 className="font-black text-slate-950">Acceso del paciente</h4><p className="text-xs text-slate-600">Canal seguro para revisión. Todavía no constituye aceptación ni firma.</p></div>{!active&&canIssue&&<button disabled={busy} onClick={()=>void create()} className="rounded-xl bg-dentia-primary px-4 py-2 text-sm font-black text-white">Generar acceso</button>}</div>{error&&<Alert tone="error">{error}</Alert>}
  {active&&<div className="mt-3 grid gap-2 text-sm md:grid-cols-2"><p><b>Estado:</b> {active.status}</p><p><b>Correo:</b> {active.recipient_masked}</p><p><b>Expira:</b> {new Date(active.expires_at).toLocaleString()}</p><p><b>Última actividad:</b> {new Date(active.last_activity_at).toLocaleString()}</p><div className="flex gap-2 md:col-span-2">{canReissue&&<button disabled={busy} onClick={()=>void create(true)} className="rounded-lg border px-3 py-2 font-bold">Reemitir</button>}{canRevoke&&<button disabled={busy} onClick={()=>void revoke(active)} className="rounded-lg border border-red-200 px-3 py-2 font-bold text-red-700">Revocar acceso</button>}</div></div>}
  {issued?.public_url&&<div role="dialog" aria-modal="true" aria-label="Enlace nuevo de consentimiento" className="mt-4 rounded-xl border bg-white p-4"><Alert tone="warning">Este enlace se muestra una sola vez. Al reemitir se invalida el anterior.</Alert><div className="my-4 flex justify-center"><QRCodeSVG value={issued.public_url} size={190} level="M" title="QR del enlace seguro de consentimiento" /></div><input ref={linkInputRef} readOnly value={issued.public_url} aria-label="Enlace seguro de consentimiento" className="w-full rounded-lg border border-slate-300 bg-slate-50 px-3 py-2 text-xs" /><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>void copyIssuedLink()} className="rounded-lg border px-3 py-2 font-bold">{copyState==="copied"?"Enlace copiado":"Copiar enlace"}</button>{copyState==="manual"&&<button type="button" onClick={selectIssuedLink} className="rounded-lg border px-3 py-2 font-bold">Seleccionar enlace</button>}<button onClick={()=>window.print()} className="rounded-lg border px-3 py-2 font-bold">Imprimir QR</button><button onClick={()=>setIssued(null)} className="rounded-lg border px-3 py-2">Cerrar</button></div>{copyState==="manual"&&<p role="alert" className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900">No fue posible copiar automáticamente. Mantenga presionado o seleccione el enlace para copiarlo.</p>}</div>}
  {clarifications.length>0&&<div className="mt-4"><h5 className="text-sm font-black">Aclaraciones</h5>{clarifications.map(item=><div key={item.id} className="mt-2 rounded-lg bg-white p-3 text-sm"><p>{item.message||"El paciente solicitó una aclaración."}</p><p className="text-xs text-slate-500">{new Date(item.requested_at).toLocaleString()} · {item.status}</p>{item.status==="OPEN"&&canManageClarifications&&<button onClick={async()=>{await resolveConsentClarification(instanceId,item.id);await load();}} className="mt-2 text-xs font-black text-emerald-700">Marcar atendida</button>}</div>)}</div>}
  {canViewAudit&&<details className="mt-4"><summary onClick={()=>{if(!audit.length)void listConsentAccessAudit(instanceId).then(setAudit);}} className="cursor-pointer text-sm font-black">Ver auditoría del acceso</summary>{audit.map(item=><p key={item.id} className="mt-2 text-xs text-slate-600">{new Date(item.occurred_at).toLocaleString()} · {item.action} · {item.result}</p>)}</details>}</section>;
}
